# Generated by Django 6.0.1 on 2026-01-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('salute', models.PositiveIntegerField(default=50)),
                ('attacco', models.PositiveIntegerField(default=50)),
                ('difesa', models.PositiveIntegerField(default=50)),
                ('attacco_speciale', models.PositiveIntegerField(default=50)),
                ('difesa_speciale', models.PositiveIntegerField(default=50)),
                ('velocita', models.PositiveIntegerField(default=50)),
            ],
        ),
    ]
